name: Matrix with java and spring boot

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]


jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]

    steps:

      - name: checkout code
        uses: actions/checkout@v3

      - name: setup java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: run test
        run: mvn clean test



