name: spring boot Matrix test

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]


jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [17]

    name: Java ${{ matrix.java }} on ${{ matrix.os }}

    steps:

      - name: checkout code
        uses: actions/checkout@v3

      - name: setup java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: run test
        run: mvn clean test



